fix various test tests failing.
they seemed to break due to a NoSuchMethodError using scala.collection.JavaConverters.seqAsJavaList from Java. But why did they work before?