attempt to fix Thread leaked of ForkJoinPool.commonPool-worker-1
There was an assertion failure:
```
sbt.ForkMain$ForkError: java.lang.AssertionError: Thread leaked: Thread[ForkJoinPool.commonPool-worker-1,4,main] (alive) TIMED_WAITING
--- its stacktrace:
at java.base@11.0.8/jdk.internal.misc.Unsafe.park(Native Method)
at java.base@11.0.8/java.util.concurrent.locks.LockSupport.parkUntil(LockSupport.java:275)
at java.base@11.0.8/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1619)
at java.base@11.0.8/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

with a preceding exception (in the very beginning of output):
```
java.lang.RuntimeException: ForkJoinPool initialized too early, IdeaForkJoinWorkerThreadFactory ignored
	at com.intellij.concurrency.PoisonFactory.<init>(PoisonFactory.java:9)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinPool.newInstanceFromSystemProperty(ForkJoinPool.java:2329)
	at java.base/java.util.concurrent.ForkJoinPool.<init>(ForkJoinPool.java:2345)
	at java.base/java.util.concurrent.ForkJoinPool$1.run(ForkJoinPool.java:3201)
	at java.base/java.util.concurrent.ForkJoinPool$1.run(ForkJoinPool.java:3199)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.ForkJoinPool.<clinit>(ForkJoinPool.java:3199)
	at com.github.benmanes.caffeine.cache.Caffeine.getExecutor(Caffeine.java:307)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.<init>(BoundedLocalCache.java:235)
	at com.github.benmanes.caffeine.cache.WS.<init>(WS.java:35)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.github.benmanes.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(LocalCacheFactory.java:98)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3357)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3353)
	at com.github.benmanes.caffeine.cache.Caffeine.build(Caffeine.java:995)
	at com.intellij.openapi.util.IconLoader.<clinit>(IconLoader.java:60)
	at org.jetbrains.plugins.scala.icons.Icons.<clinit>(Icons.java:24)
	at org.jetbrains.sbt.Sbt$.<clinit>(Sbt.scala:57)
	at org.jetbrains.sbt.codeInspection.typeAnnotation.SbtAnnotationInspectionTest.<init>(SbtAnnotationInspectionTest.scala:16)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at junit.framework.TestSuite.createTest(TestSuite.java:60)
	at junit.framework.TestSuite.addTestMethod(TestSuite.java:307)
	at junit.framework.TestSuite.addTestsFromTestCase(TestSuite.java:150)
	at junit.framework.TestSuite.<init>(TestSuite.java:129)
	at org.junit.internal.runners.JUnit38ClassRunner.<init>(JUnit38ClassRunner.java:74)
	at org.junit.internal.builders.JUnit3Builder.runnerForClass(JUnit3Builder.java:11)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runner.Computer.getRunner(Computer.java:40)
	at org.junit.runner.Computer$1.runnerForClass(Computer.java:31)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:101)
	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:87)
	at org.junit.runners.Suite.<init>(Suite.java:81)
	at org.junit.runner.Computer.getSuite(Computer.java:28)
	at org.junit.runner.Request.classes(Request.java:75)
	at org.junit.runner.Request.classes(Request.java:91)
	at com.novocode.junit.JUnitRunner$1.execute(JUnitRunner.java:124)
	at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:413)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

(cherry picked from commit 70fdce0c65ebe7442022865490c4d93a2d55120c)