[tests] avoid flaky NPE in tests by waiting for all background tasks to finish #WI-75722 #KTIJ-9718
```
java.lang.NullPointerException: Cannot invoke "com.intellij.psi.PsiElement.getIcon(int)" because the return value of "com.intellij.refactoring.classMembers.MemberInfoBase.getMember()" is null
	at com.intellij.refactoring.ui.AbstractMemberSelectionTable.getMemberIcon(AbstractMemberSelectionTable.java:431)
	at com.intellij.refactoring.ui.AbstractMemberSelectionTable.calculateMemberInfoData(AbstractMemberSelectionTable.java:146)
```