force latest version of log4j to avoid conflicts with platform libraries (there was NoSuchMethodError in jps compile server if running from our tests)