Add JUnit 5 Jupiter test dependency
Update to 242.16677.15 resulted in test compilation failures with `java.lang.NoClassDefFoundError: org/opentest4j/AssertionFailedError`.
This class is a part of opentest4j, a transitive dependency of junit-jupiter-api, which is a `provided` dependency in a lot of platform modules such as testFramework.