HighlightingPerformanceTest is causing me some problems. It was getting NullPointerException in DelegatingProcessIndicatorEx, maybe there was no ProgressIndicator available during the test? I changed DelegatingProcessIndicatorEx to handle the missing ProgressIndicator, and this led to the next problem in this test:
ERROR: Access to tree elements not allowed in tests./Users/jason/code/scala-idea-plugin/testdata/mockScalaLib/scala.jar!/scala/Predef.class

I also had problems where all tests run after this one in a suite would fail, but this change seems to have fixed this. Let me know if you see this problem, too.

git-svn-id: http://svn.jetbrains.org/idea/Trunk/scala@26504 59f64563-22e8-0310-8d2c-98a15e1539f2