StubIndexTest_2_12 test actual collection elements instead of just size
on TeamCity this test sometimes fail with unclear message:
`sbt.ForkMain$ForkError: java.lang.AssertionError: expected:<14> but was:<13>`
Lets test actual elements to see what is missing in test failure messages.