tests: use https protocol instead of git in SbtProjectImportingTest.testSCL14635
- otherwise an error is produced during the project import:
>fatal: remote error: The unauthenticated git protocol on port 9418 is no longer supported.
>Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
>java.lang.RuntimeException: Nonzero exit code (128): git clone --depth 1 git://github.com/JetBrains/sbt-idea-plugin /home/builduser/.sbt/1.0/staging/519241457c8ee019962d/sbt-idea-plugin