don't use testframework classes in production
it leads to NoClassDefFoundError in 2021.1

(cherry picked from commit 95a99b106681c347c07a37b6c6406f64032b85f7)