update bloop to 1.4.0-RC1-94-a2be783d. Addresses NoClassDefFoundError using bloop launcher. #SCL-17095 fixed
(cherry picked from commit 05c394f8aa03f8b9bb7b140392113f73aea7e836)