[psi] add an explicit override for `getPackageName` in ScalaCodeFragment #IDEA-382065
`JavaCodeFragment` now has a default method with this name that returns `null` that collides with `getPackageName` from `PsiClassOwner` via `ScalaFileImpl`.

Explicit override resolves the following compilation error: `cannot override a concrete member without a third member that's overridden by both (this rule is designed to prevent accidental overrides)`