worksheet: add fast util jar for to compiler server classpath (fix WorksheetPlainCompileLocallyRunLocallyIntegrationTest)
required after migration to latest IDEA 211 version, otherwise it fails with
java.lang.ClassNotFoundException: it.unimi.dsi.fastutil.ints.Int2ObjectMap

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.jetbrains.plugins.scala.nailgun.Utils.loadAndSetupMainClass(Utils.java:16)
    at org.jetbrains.plugins.scala.nailgun.MainLightRunner.runMainMethod(MainLightRunner.java:27)
    at org.jetbrains.plugins.scala.nailgun.MainLightRunner.main(MainLightRunner.java:22)
  Caused by: java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/ints/Int2ObjectMap
    at org.jetbrains.jps.incremental.Utils.<clinit>(Utils.java:24)
    at org.jetbrains.jps.incremental.scala.remote.Main$.setup(Main.scala:50)
    at org.jetbrains.jps.incremental.scala.remote.Main.setup(Main.scala)
    ... 7 more
  Caused by: java.lang.ClassNotFoundException: it.unimi.dsi.fastutil.ints.Int2ObjectMap
    at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
    ... 10 more
```